-- =====================================================================
-- Customer Shopping Behavior — Exploratory Data Analysis (SQL)
-- =====================================================================
-- Database : MySQL
-- Table    : customer
-- Source   : Cleaned dataset produced by notebooks/customer-shopping-behavior.ipynb
--
-- This file contains 10 business-driven analytical questions exploring
-- revenue, discounts, product ratings, shipping, subscriptions, customer
-- segmentation, and demographics.
-- =====================================================================


-- Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as total_revenue
from customer
group by gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount > (select avg(purchase_amount) from customer);


-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating), 2) as avg_review_rating
from customer
group by item_purchased
order by avg_review_rating desc
limit 5;


-- Q4. Compare the average purchase amount between Standard and Express shipping.
select shipping_type, round(avg(purchase_amount), 2) as avg_shipping_purchase_amount
from customer
where shipping_type = 'Express' or shipping_type = 'Standard'
group by shipping_type
order by avg_shipping_purchase_amount;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue
--     between subscribers and non-subscribers.
select
    subscription_status,
    count(*) as total_customer,
    round(avg(purchase_amount), 2) as avg_spend,
    round(sum(purchase_amount), 2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select
    item_purchased,
    round(sum(discount_applied = 'Yes') * 100.0 / count(*), 2) as discount_purchase_pct
from customer
group by item_purchased
order by discount_purchase_pct desc
limit 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total
--     number of previous purchases, and show the count of each segment.
select
    case
        when previous_purchases = 1 then 'New'
        when previous_purchases <= 10 then 'Returning'
        else 'Loyal'
    end as customer_segment,
    count(*) as customer_count
from customer
group by customer_segment
order by customer_count;


-- Q8. What are the top 3 most purchased products within each category?
with cte as (
    select item_purchased, category, count(*) as item_count
    from customer
    group by item_purchased, category
),
cte1 as (
    select *, rank() over (partition by category order by item_count desc) as rk
    from cte
)
select category, item_purchased, item_count
from cte1
where rk <= 3
order by category;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases)
--     also likely to subscribe?
select
    subscription_status,
    count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;


-- Q10. What is the revenue contribution of each age group?
select age_group, sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;
